### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shrikant_mage611.elite_mapping' doesn't exist

### ISSUE THREAD

**Issue by ridesafer** [vehiclefits/vfmagento#51] opened 2013-08-15 18:46 UTC
This is as far as the error message goes when attempting to delete a product from the database. Not sure where to go from here.

![capture](https://f.cloud.github.com/assets/5239262/970707/f560ad8c-05da-11e3-9136-f3d6d73a1262.JPG)

**Comment by joshribakoff** [comment] 2013-08-15 19:24
Duplicate of #43

**Closed as completed by joshribakoff** 2013-08-15 19:24 UTC
Labels: duplicate

**Comment by ridesafer** [comment] 2013-08-15 19:42
But that post doesn't outline what the fix was. Could you point me in the right direction?
